A TS fix for PPR (#86)
* A TS fix for PPR

PPR uses strict typescript checking. This fix is required for PPR to use these common components.
Plus, fix large number of unit test failures
Updating the test package resolves numerous unit test errors that have the form
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:1884
      TypeError: Cannot read property '_transitionClasses' of undefined

* Adjust as per PR comment